/**
 * Generates src/data/photos.ts from whatever sits in public/photos.
 *
 * Run after adding or removing images:  pnpm photos
 *
 * Dimensions and blur placeholders are baked at build time so the gallery ships
 * zero layout shift and never resolves them at request time. Source files are
 * read-only here — the originals are the masters and are never rewritten.
 */
import { readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";

const PHOTO_DIR = join(process.cwd(), "public", "photos");
const OUT = join(process.cwd(), "src", "data", "photos.ts");
const BLUR_WIDTH = 16;

const numeric = (a: string, b: string) =>
  (Number.parseInt(a, 10) || 0) - (Number.parseInt(b, 10) || 0) || a.localeCompare(b);

const files = (await readdir(PHOTO_DIR))
  .filter((name) => /\.(jpe?g|png|webp|avif)$/i.test(name))
  .sort(numeric);

const photos = await Promise.all(
  files.map(async (file) => {
    const image = sharp(join(PHOTO_DIR, file));
    const { width = 0, height = 0 } = await image.metadata();
    const buffer = await image.resize(BLUR_WIDTH).webp({ quality: 20 }).toBuffer();
    return {
      src: `/photos/${file}`,
      width,
      height,
      blurDataURL: `data:image/webp;base64,${buffer.toString("base64")}`,
    };
  }),
);

await writeFile(
  OUT,
  `// GENERATED by scripts/build-photo-manifest.ts — do not edit by hand.
export type Photo = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const photos: readonly Photo[] = ${JSON.stringify(photos, null, 2)} as const;
`,
);

console.log(`Wrote ${photos.length} photos to ${OUT}`);
