// GENERATED by scripts/build-photo-manifest.ts — do not edit by hand.
export type Photo = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const photos: readonly Photo[] = [
  {
    src: "/photos/1.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAsABUB8JZQC7ADJgBahAAD+3h8FWUx97AF2AoF53qLHTjd9BWYgGH7vnUzBYwNB+Yvb+OSB5z6RYlNYAAAA",
  },
  {
    src: "/photos/2.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACQAQCdASoQAAsABUB8JZQAAhdBGIAA/vFtLxZ6BuU8HE5fXmGefyAA",
  },
  {
    src: "/photos/3.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAwAgCdASoQAAsABUB8JYwC7AEPCLcb5aRVAAD+7ZviXl/YrOBg8ohE4ThA9RTFXYJjEkpKjZHXCtPOOf9rUS6P6L7zfpDb+9qAAA==",
  },
  {
    src: "/photos/4.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoQAAsABUB8JQBOj+ADBKt1YGHAAPX+5iFsj8IuZLppjs+iwArNltI7NbrY9E1C8gAAAA==",
  },
  {
    src: "/photos/5.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAsABUB8JYwCw7D0rCqtDgAA/mTT5KWTtZiLnn5r3GUuG0l2D5IDs0n+pBgoy8gEvqVMLGfWQAmBdeMAAA==",
  },
  {
    src: "/photos/6.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoQAAsABUB8JYwCdADzY36AAP7c013ub0Ru2ox3KrUtzUysWpLQ0AAA",
  },
  {
    src: "/photos/7.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoQAAsABUB8JYwCdAD1d8gjSAAA/tHdAd/Weg8O81yxGCw6OiH0JaQ84zGGmMyhoAAAAA==",
  },
  {
    src: "/photos/8.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAwAgCdASoQAAsABUB8JZQCdH8AGBiWAvwwAAD9+sEBqLfHnH3qnvw2xqLQozlIOntnOzwAAAA=",
  },
  {
    src: "/photos/9.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoQAAsABUB8JYwCdAD0MWUgAP7AMFWmPkFG1aCy9VU9zTy2NhOIOYAA",
  },
  {
    src: "/photos/10.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoQAAsABUB8JZgCdAENodDlwAAA/pcdLR7xwfB10EDo5i5fLYiDrh0hYVe9c0S9oq7OAAAA",
  },
  {
    src: "/photos/11.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAwAgCdASoQAAsABUB8JQBOj+ACuObS609YAADOHff0vDej3OLps/BqZwfE5gwj9VU2pQAA",
  },
  {
    src: "/photos/12.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoQAAsABUB8JYwCdAD0MVFP4YAA/tDCkZFO0etk2kq1mNrZiTbTD5nwAAA=",
  },
  {
    src: "/photos/13.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoQAAsABUB8JQBOgCIgpVLQAPzXYBdb1yK5w4ZTTse8VNV3eOmTOHKkSNnoN4MZa9Dp2EOr0v2s7qfgAAA=",
  },
  {
    src: "/photos/14.jpg",
    width: 2304,
    height: 1536,
    blurDataURL:
      "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoQAAsABUB8JYwCdH8AFdjGAAD+3JQpLY8dghizMmLe7+4/SpwIOuK5AA1FOnuVAAA=",
  },
] as const;
